# Generated by Django 6.0.4 on 2026-04-10 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('blue', 'Azul - Cisco'), ('green', 'Verde - Seguridad'), ('orange', 'Naranja - Wireless'), ('purple', 'Púrpura - Cloud'), ('red', 'Rojo - Troubleshooting'), ('gray', 'Gris - General')], default='blue', max_length=20)),
                ('icono', models.CharField(blank=True, help_text='Emoji o clase de icono', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(blank=True, help_text='Breve descripción para la lista de artículos', max_length=500)),
                ('nivel_dificultad', models.CharField(choices=[('principiante', '🟢 Principiante (CCNA)'), ('intermedio', '🟡 Intermedio (CCNP)'), ('avanzado', '🟠 Avanzado (CCIE)'), ('experto', '🔴 Experto / Arquitectura')], default='principiante', max_length=20)),
                ('etiquetas', models.CharField(blank=True, help_text='Separadas por comas: Cisco, Packet Tracer, VLAN, etc.', max_length=300)),
                ('imagen_destacada', models.ImageField(blank=True, help_text='Imagen principal del artículo', null=True, upload_to='posts/featured/%Y/%m/')),
                ('imagen_banner', models.ImageField(blank=True, help_text='Imagen grande para el encabezado', null=True, upload_to='posts/banners/%Y/%m/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('destacado', models.BooleanField(default=False, help_text='Aparecerá en la sección de destacados')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('meta_descripcion', models.CharField(blank=True, help_text='Descripción para Google (SEO)', max_length=160)),
                ('palabras_clave', models.CharField(blank=True, help_text='Palabras clave para SEO', max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='posts/adjuntos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='posts.post')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-fecha_publicacion'], name='posts_post_fecha_p_348aed_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='posts_post_estado_9a8097_idx'),
        ),
    ]
